travis:
  secure:
    BINSTAR_TOKEN: BGnYElAQuoMab3AUmWkTBgUjXUwFSdUO5nxveEnqQP1H77gLWghL5uRTjTJJsOMdzAWxH2GuhX/4LA+PG1QNPGWgmC4XwFQ8t+Vi7YrLmQNKmM+DMhj7BYKayhO1vhr6pXYzdVkDPcY+l6Di3uKGYBVpuf3xnhv0NE6gevVybfeE4wrIO3rka8lB6/0W0TaGVV3hTXsCu/Vov+WyOKi05G0/M47uwc+min++Nbn5VJPrH1TI8fxd4ZQJrpj9he5xqPBwG8fmEqcnmTneNPMy97YMlKT4bXtztkClD43ASNWl1Wm7b674Y/JQKCGR2lo0/d9vttFxiHydpuzk27YLL+Xz+6bxIScVgVcfOYwZi88qC5XqUo1rNPoxLRNqN7vd3Ye0xWYivw4GaAw7g/zhmJ5nsmzR8hAMmX48tBhtuZ75/F9hHcPFK1thJoeidxVrIM2PMGqhZRGVSRieH5JJRCVE2GWwm6SGkX8JfpP302bQ45Lhj4UV+wxCddGLL+bDmiJYZWA0xSPH10QuYBfoIki2iVvTngcjTyx4irbStrHL5NPIS1LgPwb51CjCU7pnhD2rlXJl1MIdpi/2ycdax3Udwan27C3xPJV5g4cGY/Cd/WCaX0S9TwDsBW14GsX4TsFtzx7l+KaCSrt1ajfCX1wY8FusW6Tw2HVytAlH7Ok=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
