travis:
  secure:
    BINSTAR_TOKEN: N3k17P7j4CIvS1rUu+zTTjQtnLQU6OwSzGEsdx/TexZJZVzy05fzGMIEZSuNurADj5+VlGaLQ3RZuzehC4IM+pf9bijeRril4nFumLIMpkL51fygUz11HtKqPW2eMIkVqoVZMPzLtPyylkotRflfYhHlWPChQzzdJHrYky7x6IdWTjh4SsoZRM7bg8oq/45hpKxdyURo//2BHsioBlWa1nxMBamTFGjzAnpmvUqJJ4pGKkad5b1JINfSD7kvgpMC8eERRU0VRRbMhgfqK3DRggMAh9uMBi5k4b08ehQT6yWyyfrTvNd1yMoic438eqKgy9LiO8EIaZ4CZKcwRVMXwAoW5G1sQDDCOFsqsDLhpXBB1GI66ezm9ZJmMDCTwvVm4Stqzj1kEddBhm8P9JgYCFVOAtzqePHMXTN+qvVopZvqDMV7dwRZz6kogxaVe02UWsZKcYvFuC041GYJ7rsITVnZRIfR+6aGismrbHzIV1C384W+VPx+r+oAeT6V76PqVJeXUq+b132nVzeNhyNHLC2F2RlPNkL5jNvQ530Wwoj3SicTr2pjU9edowwz0BYYPvGkWUHgT1XnNNAKNq61GNAZniOiX4BvrJzuwD2UYiYpq9aBX4Jswf9KDkxoGlJ+tk6CuDGcMFw5BznUgvrugVvG0582DhoRprTdqcUlBlA=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
